blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, MaterialDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blogs_homepage'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('view/<int:pk>/<str:slug>', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/<str:slug>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/<str:slug>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Materials(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='product/', verbose_name='изображение/превью', **NULLABLE)
    created_at = models.DateField(verbose_name='дата создания', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмоторы')

    def __str__(self):
        return f'{self.title}, {self.content}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.models import Materials


class BlogListView(ListView):
    model = Materials
    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Materials
    fields = ('title', 'content',)
    success_url = reverse_lazy('blog:blogs_homepage')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Materials
    fields = ('title', 'content',)
    success_url = reverse_lazy('blog:blogs_homepage')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk'), self.kwargs.get('slug')])


class MaterialDetailView(DetailView):
    model = Materials

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Materials
    success_url = reverse_lazy('blog:blogs_homepage')

blog/templates/blog/materials_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить блог "{{ object.title}}"? </p>
                    <button type="submit" class="btn btn-danger">
                        Подтвердить
                    </button>
                    <a href="{% url 'blog:blogs_homepage' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/materials_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="card">
    {% if object.preview %}
    <img src="{{ object.preview.url }}" class="card-img-top" alt="{{ object.title }}">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{ object.title }} ({{object.slug}})</h5>
        <p class="card-text">{{ object.content|truncatewords:20 }}</p>
    </div>
    <div class="card-footer">
        <small class="text-muted">Дата создания: {{ object.created_at }}</small>
        Просмотры: {{ object.views_count }}
    </div>
</div>


{% endblock %}

blog/templates/blog/materials_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class =card >
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                Сохранить
                                {% else %}
                                Опубликовать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/materials_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Blogs</h1>
    <a href="{% url 'blog:create' %}" class="btn btn-primary">Опубликовать пост</a>

</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.content }}</li>
                    </ul>
                    <div class="btn-group">
                        <a href="{% url 'blog:view' object.pk object.slug %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">view</a>
                        <a href="{% url 'blog:edit' object.pk object.slug %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">edit</a>
                        <a href="{% url 'blog:delete' object.pk object.slug  %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">delete</a>
                    </div>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}